import nbformat as nbf

def generate_notebook(target_column, metric_name):
    """
    This is the Notebook Agent. It writes a complete Jupyter Notebook (.ipynb) 
    containing the exact code required to replicate the AI's machine learning process.
    """
    # 1. Create a blank notebook
    nb = nbf.v4.new_notebook()

    # 2. Add a Markdown Cell for explanation
    intro_text = f"""# Automated Machine Learning Code
This notebook contains the exact code generated by the Autonomous AI Data Scientist.
**Target Column:** `{target_column}`
**Evaluation Metric:** `{metric_name}`"""
    nb.cells.append(nbf.v4.new_markdown_cell(intro_text))

    # 3. Add a Code Cell for Imports
    imports_code = """import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import accuracy_score, r2_score
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.linear_model import LogisticRegression, LinearRegression
from sklearn.svm import SVC, SVR
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor
from sklearn.naive_bayes import GaussianNB
from xgboost import XGBClassifier, XGBRegressor"""
    nb.cells.append(nbf.v4.new_code_cell(imports_code))

    # 4. Add a Code Cell for Data Loading & Preprocessing
    preprocess_code = f"""# Load the cleaned dataset
df = pd.read_csv('cleaned_dataset.csv')

X = df.drop(columns=['{target_column}'])
y = df['{target_column}']

# Encode text features to numbers
for column in X.select_dtypes(include=['object']).columns:
    le = LabelEncoder()
    X[column] = X[column].astype(str)
    X[column] = le.fit_transform(X[column])

# Convert target if it is categorical text
if y.dtype == 'object':
    le_y = LabelEncoder()
    y = le_y.fit_transform(y.astype(str))

# Split and scale the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)"""
    nb.cells.append(nbf.v4.new_code_cell(preprocess_code))

    # 5. Add a Code Cell for Model Training (Checking if it is Classification or Regression)
    if metric_name == "Accuracy":
        model_code = """# Initialize Classification Models
models = {
    "Logistic Regression": LogisticRegression(max_iter=1000, random_state=42),
    "Random Forest": RandomForestClassifier(random_state=42),
    "Decision Tree": DecisionTreeClassifier(random_state=42),
    "Naive Bayes": GaussianNB(),
    "SVM": SVC(random_state=42),
    "XGBoost": XGBClassifier(random_state=42, eval_metric='logloss')
}

# Train and Compare
results = []
for name, model in models.items():
    model.fit(X_train_scaled, y_train)
    predictions = model.predict(X_test_scaled)
    score = accuracy_score(y_test, predictions)
    results.append({"Model": name, "Accuracy": score})

results_df = pd.DataFrame(results).sort_values(by="Accuracy", ascending=False)
print(results_df)"""
    else:
        model_code = """# Initialize Regression Models
models = {
    "Linear Regression": LinearRegression(),
    "Random Forest": RandomForestRegressor(random_state=42),
    "Decision Tree": DecisionTreeRegressor(random_state=42),
    "SVM": SVR(),
    "XGBoost": XGBRegressor(random_state=42)
}

# Train and Compare
results = []
for name, model in models.items():
    model.fit(X_train_scaled, y_train)
    predictions = model.predict(X_test_scaled)
    score = r2_score(y_test, predictions)
    results.append({"Model": name, "R-Squared Score": score})

results_df = pd.DataFrame(results).sort_values(by="R-Squared Score", ascending=False)
print(results_df)"""
    
    nb.cells.append(nbf.v4.new_code_cell(model_code))

    # 6. Save the notebook to a file
    notebook_filename = "Generated_ML_Code.ipynb"
    with open(notebook_filename, 'w') as f:
        nbf.write(nb, f)
        
    return notebook_filename